User service.
mikhailgomziak/SportsHub pull request #24
Opened 2021-07-05 09:27 UTC by AverageTryHard

2021-07-05 09:46 UTC, yar0m commented on app/controllers/admin/users_controller.rb
> +      service = UserService::ChangeStatus.new
Назви сервіс так як ми обговорювали, `UserService::Block` для блокування та ще один для розблокування.
Також винеси відправку емейлу в сервіс - це також частина логіки яка стосується видалення.

2021-07-05 09:48 UTC, yar0m requested changes

2021-07-05 09:48 UTC, yar0m commented on app/services/user_service/change_status.rb
> +      if user.save
ти запускав код? тут буде помилка.

Додай тести

2021-07-20 15:12 UTC, AverageTryHard commented on app/controllers/admin/users_controller.rb
> +      service = UserService::ChangeStatus.new
Что имеено вынести? Одну строку?

2021-07-20 15:30 UTC, closed without merging